// CableTwin decision recommender — local, explainable inference.
// A softmax regression trained by scripts/train-recommender.mjs on an
// incident history GENERATED by the twin itself (synthetic, documented in
// the model's provenance). It assists the decision; it never replaces the
// production manager and never sends anything to a machine.

import { RECOMMENDER_MODEL } from "./recommender-model.js";
import { FEATURE_NAMES, extractFeatures } from "./recommender-features.js";

export function recommendPlan(scenario, impact, plans, model = RECOMMENDER_MODEL) {
  const features = extractFeatures(scenario, impact, plans);
  const x = features.map((value, i) => (value - model.means[i]) / (model.stds[i] || 1));

  const logits = model.classes.map((_, k) =>
    model.biases[k] + model.weights[k].reduce((acc, w, j) => acc + w * x[j], 0));
  const maxLogit = Math.max(...logits);
  const exps = logits.map((logit) => Math.exp(logit - maxLogit));
  const sum = exps.reduce((acc, value) => acc + value, 0);
  const probs = exps.map((value) => value / sum);

  const top = probs.indexOf(Math.max(...probs));
  const factors = x
    .map((xNorm, j) => ({
      name: FEATURE_NAMES[j] ?? model.featureNames[j],
      raw: features[j],
      contribution: model.weights[top][j] * xNorm,
    }))
    .sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution))
    .slice(0, 3);

  return {
    strategyId: model.classes[top],
    confidence: probs[top],
    probabilities: Object.fromEntries(model.classes.map((id, k) => [id, probs[k]])),
    topFactors: factors,
    model: {
      version: model.version,
      kind: model.kind,
      trainedAt: model.trainedAt,
      datasetSize: model.datasetSize,
      testAccuracy: model.testAccuracy,
      dataProvenance: model.dataProvenance,
      policy: model.policy,
    },
  };
}
